name: Daily Summary Job

on:
  schedule:
    - cron: "0 17 * * *" # every day at 00:00 UTC
  workflow_dispatch:

jobs:
  run-summary:
    runs-on: ubuntu-latest

    steps:
      - name: Call Backend API
        run: |
          curl -k -X POST https://e759-2405-8180-203-4b20-6cfb-fc18-2e21-1977.ngrok-free.app/api/summary/generate \
          -H "Authorization: Bearer ${{ secrets.CRON_SECRET }}"